name: CI Main Branch

on:
  push:
    branches:
      - main

jobs:
  create-docs:
    name: Generate documentation
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-doc:debian-bookworm_GCC-14_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ./runme --actions docs
        tar -czf documentation.tar.gz -C build/docs html -C latex refman.pdf
      artifact_path: 'documentation.tar.gz'
      artifact_name: 'documentation'

  create-coverage:
    name: Generate coverage report
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-gcc:debian-bookworm_GCC-14_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ./runme --mode coverage --actions coverage
        tar -czf coverage.tar.gz -C build/coverage .
      artifact_path: 'coverage.tar.gz'
      artifact_name: 'coverage'

  test-gcc:
    name: Check and generate binaries using GCC
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-gcc:debian-bookworm_GCC-14_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ./runme --actions test
        tar -czf gcc-libs.tar.gz -C build/lib .
      artifact_path: 'gcc-libs.tar.gz'
      artifact_name: 'gcc-libs'

  test-clang:
    name: Check and generate binaries using Clang
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-clang:debian-bookworm_CLANG-19_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ./runme --actions test
        tar -czf clang-libs.tar.gz -C build/lib .
      artifact_path: 'clang-libs.tar.gz'
      artifact_name: 'clang-libs'

  leak-gcc:
    name: Check memory leaks on GCC
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-gcc:debian-bookworm_GCC-14_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ulimit -n 1024
        ./runme --mode memleak --actions memleak || true

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [create-docs,create-coverage,test-gcc,test-clang,leak-gcc]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Get version number
      run: |
        autoreconf --install
        echo "VERSION=$(./configure --version | head -n1 | sed 's/.* \([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/')" >> $GITHUB_ENV
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: |
          Release for ${{ env.VERSION }}
          - GCC compiled libraries
          - Clang compiled libraries
          - Documentation
          - Coverage
    - name: Download documentation
      uses: actions/download-artifact@v4
      with:
        name: documentation
    - name: Download Coverage
      uses: actions/download-artifact@v4
      with:
        name: coverage
    - name: Download Clang libs
      uses: actions/download-artifact@v4
      with:
        name: clang-libs
    - name: Download GCC libs
      uses: actions/download-artifact@v4
      with:
        name: gcc-libs
    - name: Upload GCC libraries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gcc-libs.tar.gz
        asset_name: gcc-libs.tar.gz
        asset_content_type: application/gzip
    - name: Upload Clang libraries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./clang-libs.tar.gz
        asset_name: clang-libs.tar.gz
        asset_content_type: application/gzip
    - name: Upload documentation to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./documentation.tar.gz
        asset_name: documentation.tar.gz
        asset_content_type: application/gzip
    - name: Upload coverage to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./coverage.tar.gz
        asset_name: coverage.tar.gz
        asset_content_type: application/gzip
    - name: Change to GitHub Pages branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git reset --hard
        git checkout gh-pages
        git clean -fd
    - name: Download documentation
      uses: actions/download-artifact@v4
      with:
        name: documentation
    - name: Download Coverage
      uses: actions/download-artifact@v4
      with:
        name: coverage
    - name: Uncompress documentation and coverage
      run: |
        rm -rf docs || true
        rm -rf coverage || true
        mkdir docs || true
        mkdir coverage || true
        tar -xzf documentation.tar.gz -C docs && rm documentation.tar.gz
        tar -xzf coverage.tar.gz -C coverage && rm coverage.tar.gz
    - name: Deploy gh-pages
      run: |
        git add docs/
        git add coverage/
        git commit -m "Update GitHub Pages documentation for version ${{ env.VERSION }}"
        git push --force --set-upstream origin gh-pages
