name: CI Push

on:
  push:
    branches-ignore:
      - main

jobs:

  create-coverage:
    name: Generate coverage report
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-gcc:debian-bookworm_GCC-14_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ./runme --mode coverage --actions coverage

  test-gcc:
    name: Check and generate binaries using GCC
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-gcc:debian-bookworm_GCC-14_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ./runme --actions check

  test-clang:
    name: Check and generate binaries using CLANG
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-clang:debian-bookworm_CLANG-19_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ./runme --actions check

  leak-gcc:
    name: Check memory leaks on GCC
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-gcc:debian-bookworm_GCC-14_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ulimit -n 1024
        ./runme --mode memleak --actions memleak

  thread-gcc:
    name: Check thread issues on GCC
    uses: ./.github/workflows/reusable-job.yml
    with:
      docker_image: 'lopoeisr/make-gcc:debian-bookworm_GCC-14_20241202135515'
      docker_options: '--privileged --user root'
      commands: |
        ulimit -n 1024
        ./runme --mode thread --actions thread
