name: C Project CI Pipeline

on:
  push:
    branches: ["main"]

  workflow_dispatch:  # Permite ejecutar el workflow manualmente
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      release_name:
        description: 'Release name'
        required: true
  workflow_call: # Permite que este workflow sea llamado desde otros workflows
    inputs:
      after_prepare:
        description: 'Additional steps to run after prepare'
        required: false
        type: step[]
      before_tests:
        description: 'Additional steps to run before tests'
        required: false
        type: step[] # Define que puedes pasar un array de steps

jobs:
  prepare:
    name: Prepare environment
    runs-on: ubuntu-latest
    container:
      image: lopoeisr/node-pkg:1.0
      options: --privileged --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        recursive: true
    - name: Preparing environment
      run: make prepare
    - name: After preparation
      if: ${{ inputs.after_prepare }}
      run: ${{ toJson(inputs.after_prepare) }}

  documentation:
    name: Create documentation
    runs-on: ubuntu-latest
    container:
      image: lopoeisr/ubuntu-make-doc:1.0
      options: --privileged --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        recursive: true
    - name: create documentation
      run: |
        make docs && tar -czvf docs.tar.gz docs
    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: |
          ./docs.tar.gz

  build-and-test-gcc:
    name: Build, Test and Package with GCC
    runs-on: ubuntu-latest
    needs: [prepare, documentation]
    container: 
      image: lopoeisr/ubuntu-make-gcc:1.0
      options: --privileged --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        recursive: true
    - name: Prepare environment with make gtest
      run: make gtest
    - name: Download dependencies
      uses: actions/download-artifact@v3
      with:
        name: dependencies
    - name: Test preparation
      if: ${{ inputs.before_tests }}
      run: ${{ toJson(inputs.before_tests) }}
    - name: Run tests
      run: make tests
    - name: Create libraries
      run: make clean && make libs
    - name: Download documentation
      uses: actions/download-artifact@v3
      with:
        name: documentation
    - name: Package libraries
      run: |
        tar -xf docs.tar.gz
        tar -czvf gcc-libs-n-docs.tar.gz libs docs
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gcc-libs-n-docs
        path: gcc-libs-n-docs.tar.gz

  build-and-test-clang:
    name: Build, Test and Package with Clang
    runs-on: ubuntu-latest
    needs: [prepare, documentation]
    container:
      image: lopoeisr/ubuntu-make-clang:1.0
      options: --privileged --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        recursive: true
    - name: Prepare environment with make gtest
      run: make gtest
    - name: Download dependencies
      uses: actions/download-artifact@v3
      with:
        name: dependencies
    - name: Test preparation
      if: ${{ inputs.before_tests }}
      run: ${{ toJson(inputs.before_tests) }}
    - name: Run tests
      run: make tests
    - name: Create libraries
      run: make clean && make libs
    - name: Download documentation
      uses: actions/download-artifact@v3
      with:
        name: documentation
    - name: Package libraries
      run: |
        tar -xf docs.tar.gz
        tar -czvf clang-libs-n-docs.tar.gz libs docs
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: clang-libs-n-docs
        path: clang-libs-n-docs.tar.gz

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-and-test-gcc, build-and-test-clang]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        recursive: true
    - name: Get version number
      run: echo "VERSION=$(cat .version)" >> $GITHUB_ENV
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: |
          Release for ${{ env.VERSION }}
          - GCC compiled libraries
          - Clang compiled libraries
    - name: Download GCC artifact
      uses: actions/download-artifact@v3
      with:
        name: gcc-libs-n-docs
    - name: Download Clang artifact
      uses: actions/download-artifact@v3
      with:
        name: clang-libs-n-docs
    - name: Upload GCC libraries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gcc-libs-n-docs.tar.gz
        asset_name: gcc-libs-n-docs.tar.gz
        asset_content_type: application/gzip
    - name: Upload Clang libraries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./clang-libs-n-docs.tar.gz
        asset_name: clang-libs-n-docs.tar.gz
        asset_content_type: application/gzip


